package com.georgiev.builder;


public interface RequestBuilder extends AddEmployeeRequestBuilder, ChangeEmployeeRequestBuilder, DeleteEmployeeRequestBuilder, AddTimeCardRequestBuilder, AddSalesRecieptRequestBuilder, AddServiceChargeRequestBuilder, PayEmployeeRequestBuilder, FindEmployeeRequestBuilder {

}